query ($id: Int, $search: String) {
    Media (id: $id, search: $search, type: ANIME) {
        id
        duration
        description(asHtml: false)
        episodes
        bannerImage
        title {
            romaji
            english
            native
        }
        coverImage {
            large
        }
    }
}
mutation ($mediaId: Int, $status: MediaListStatus) {
    SaveMediaListEntry (mediaId: $mediaId, status: $status) {
        id
        status
    }
}